export const siteConfig = {
  name: "Voxeil Yazılım",
  brandName: "Voxeil",
  legalName: "Voxeil Yazılım ve Mühendislik",
  url: "https://voxeil.com",
  title: "Voxeil Yazılım ve Mühendislik | Web, Mobil & Dijital Dönüşüm",
  description:
    "Voxeil, Ankara merkezli yazılım şirketi. Web, mobil, e-ticaret ve dijital dönüşümde uçtan uca yazılım geliştirme sunuyoruz. Ücretsiz keşif görüşmesi.",
  logoAlt: "Voxeil Yazılım ve Mühendislik — Ankara yazılım şirketi logosu",
  footerDescription:
    "Voxeil, Ankara merkezli bir yazılım şirketidir. Web, mobil, e-ticaret ve dijital dönüşüm projelerinde iş ortaklarımıza uçtan uca yazılım çözümleri sunuyoruz.",
  keywords: [
    "voxeil",
    "voxeil yazılım",
    "voxeil yazılım şirketi",
    "yazılım şirketi",
    "ankara yazılım şirketi",
    "yazılım",
    "dijital dönüşüm",
    "ankara yazılım",
    "web geliştirme",
    "mobil uygulama",
    "otomasyon",
    "e-ticaret",
    "yazılım çözümleri",
  ],
  locale: "tr_TR",
  language: "tr",
  email: "info@voxeil.com",
  phone: "+905304010675",
  phoneDisplay: "+90 (530) 401 06 75",
  address: {
    streetAddress: "Çankaya",
    addressLocality: "Ankara",
    addressRegion: "Ankara",
    postalCode: "06690",
    addressCountry: "TR",
    full: "Çankaya, 06690 Ankara, Türkiye",
  },
  openingHours: "Mo-Fr 09:00-18:00",
  googleMapsUrl:
    "https://www.google.com/maps/search/?api=1&query=Çankaya+06690+Ankara+Türkiye",
  geo: {
    latitude: 39.9179,
    longitude: 32.8627,
  },
  social: {
    linkedin: "https://linkedin.com/company/voxeil",
    github: "https://github.com/voxeil",
    instagram: "https://instagram.com/voxeil",
    facebook: "https://facebook.com/voxeil",
    x: "https://x.com/voxeil",
    youtube: "https://youtube.com/channel/UC9J6q1C4mSyIFBe-V-iGC5g",
  },
  founders: [
    {
      name: "Ahmed Resul KURT",
      jobTitle: "UI/UX Tasarımcı & DevOps Mühendisi",
      linkedin: "https://www.linkedin.com/in/ahmed-resul-kurt-86bb17234/",
    },
    {
      name: "Bülent KOÇ",
      jobTitle: "Backend Geliştirici & Uygulama Mimarı",
      linkedin: "https://www.linkedin.com/in/bülent-deniz-koç-15a498301/",
    },
  ],
} as const;
